#Supabase関連の設定値(本番環境)
#SUPABASE_URL = "https://eojjhyjkfnynnhnmlbwb.supabase.co"
#SUPABASE_KEY = "sb_publishable_aqbiHZ2trLKYPFzQaUvVtQ_y7Nk86xl"
#STORAGE_BASE_URL = "https://eojjhyjkfnynnhnmlbwb.supabase.co/storage/v1/object/public/correct_image/"   

#Supabase関連の設定値(開発環境)
#SUPABASE_URL = "https://npqjdhighfwmbfkfzfzt.supabase.co"
#SUPABASE_KEY = "sb_publishable_0TIDEmj6p862tNALXFCSlA_If4Xkb58"
#STORAGE_BASE_URL = "https://npqjdhighfwmbfkfzfzt.supabase.co/storage/v1/object/public/correct_image"   

#Supabase関連の設定値([公開]環境開発)
SUPABASE_URL = "https://xfdxkpjbrypldprvdijw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZHhrcGpicnlwbGRwcnZkaWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyNDIxMDIsImV4cCI6MjEwNjgxODEwMn0.xz-RgP5pd2LogrLR7gVjPU2pQkvOVFIXQtKj2K3rQ9E"
STORAGE_BASE_URL = "https://xfdxkpjbrypldprvdijw.supabase.co/storage/v1/object/public/correct_image"   
